name: first-test

on: 
  push:
  pull_request:
    types: [closed, assigned, opened, reopened]

jobs:
  getinputjob:
    runs-on: ubuntu-latest
    steps:
      on: 
        workflow_dispatch:
        inputs:
          environment:
          description: 'Define env name'     
          required: true
          default: 'prod'
        branch:
          description: 'Define branch name'     
          required: true
          default: 'master'
        

  printInputs:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "Env: ${{ github.event.inputs.environment }}" 
        echo "Branch: ${{ github.event.inputs.branch }}"
