name: first-test

on: push

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "test line"
      - name
        run: |
          node -v
          npm -v
