name: first-test

on: [ push, pull_request ]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "test line"
      - name: shell command
        run: |
          df -h
          git --version
      -name: somename
        age: 43
        address: xyz
        active: true
